version: '2'

services: 
    aspnetcore:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            -"5000:5000"
        networks: 
            - todoapp-neywork


networks: 
    todoapp-neywork:
        driver: bridge