version: '2'

services: 
    aspnetcore:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - postgresserver
        depends_on:
            - "postgresserver"
        ports:
            - "5000:5000"
        networks: 
            - todoapp-network

    postgresserver:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
              POSTGRES_PASSWORD: password
              POSTGRES_USER: "postgres"
              POSTGRES_DB: "ToDoApp"
        volumes:
                - pgdata:/var/lib/postgresql/data
        networks: 
                - todoapp-network

networks: 
    todoapp-network:
        driver: bridge

volumes:
    pgdata: