version: '2'

services: 
    aspnetcoreapi:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - postgresserverdb
        depends_on:
            - "postgresserverdb"
        ports:
            - "5000:5000"
        networks: 
            - todoapp-network

    postgresserverdb:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
              POSTGRES_DB: ToDoApp
              POSTGRES_PASSWORD: password
        volumes:
                - pgdata:/var/lib/postgresql/data
        networks: 
                - todoapp-network

networks: 
    todoapp-network:
        driver: bridge

volumes:
    pgdata: