// <auto-generated />
using System;
using Demo.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Demo.db.Migrations
{
    [DbContext(typeof(AnniversaryContext))]
    [Migration("20210602080925_InitialEntities")]
    partial class InitialEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Demo.db.Entities.Occasion", b =>
                {
                    b.Property<Guid>("OccasionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<int>("OccasionTypeId")
                        .HasColumnType("integer");

                    b.HasKey("OccasionId");

                    b.HasIndex("OccasionTypeId");

                    b.ToTable("Occasions");
                });

            modelBuilder.Entity("Demo.db.Entities.OccasionType", b =>
                {
                    b.Property<int>("OccasionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("OccasionTypeName")
                        .HasColumnType("text");

                    b.HasKey("OccasionTypeId");

                    b.ToTable("OccasionTypes");
                });

            modelBuilder.Entity("Demo.db.Entities.Occasion", b =>
                {
                    b.HasOne("Demo.db.Entities.OccasionType", "OccasionType")
                        .WithMany()
                        .HasForeignKey("OccasionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OccasionType");
                });
#pragma warning restore 612, 618
        }
    }
}
